### PR TITLE
add missing import statement

### PR DESCRIPTION
**Pull request by maggu2810**
Signed-off-by: Markus Rathgeb maggu2810@gmail.com

### CODE REVIEW

**Comment by cdjackson** [comment]
I have a problem with my configuration which I need to sort out as currently the option provider is not recognised in my environment even though I've updated the target and merged master. Therefore when I save this file the formatted always removed the import automatically.

**Comment by maggu2810** [comment]
If I can help you with your configuration, let me know.

**Comment by cdjackson** [comment]
Thanks. Something is just out of sync. I was on holiday in the Canaries for the past few days and Internet wasn't quite as good as I would like. 

I'll try and reload the target again tonight. If I get stuck, I'll let you know :)

**Comment by cdjackson** [comment]
It was a stupid Eclipse issue since I also had the source bundle included, and I’d not updated my ESH source even though I’d disabled the config.core bundle… Anyway, it’s sorted now :)

**Comment by maggu2810** [comment]
Solved by: https://github.com/cdjackson/openhab2/commit/796a241ac0d458b38420fec0afb3eb59402fbb72#diff-b94a4f570dc33a74f7883038ccebca1cR18

**Pull request closed without merging**
