### PR TITLE
Zigbee

### PR DESCRIPTION
**Pull request by AlexeyIvantsov**
1) Reset flag added to ZB-stick settings.
     PAN Id is set to 0xFFFF because of ZB-stick can assign the PAN Id by himself.
     Channel Id is set to 19 - this is the channel number for TI CC2538 by default.

2) New devices were added
     http://smartenit.com/product/zbht-2/
     http://smartenit.com/product/zbmplug15/

### CODE REVIEW

**Comment by cdjackson** [comment]
> Channel Id is set to 19 - this is the channel number for TI CC2538 by default.

Are you sure this is correct? Also for the 2531? I don't think this is correct - I could be wrong, but I thought channel 11 was default?

In any case, I don't think that removing PanID and Channel is the right approach - this means that it is now not possible for the user to set these values at all, so you have completely removed the ability of the user to control the settings - why?

I also don't think that the reset approach is correct. Firstly, I don't think you should use a text field - it should be boolean. Secondly, I don't think setting this in this way is the right way to do this.

Can I suggest for now to break the PR into two - one to add the devices which we can merge now?

**Comment by AlexeyIvantsov** [comment]
Hi Chris,

"I thought channel 11 was default" - yes, you are right, channel 11 is default.
The channel 19 is correct for the 2531 and for the 2538 - I worked with both ZB-sticks.

I see the next data in ZNP document for the ZB_WRITE_CONFIGURATION command:
"4.2.4 Network specific configuration parameters
4.2.4.1 ZCD_NV_PANID
Configuration ID: 0x0083; Size: 2 bytes; Default value: 0xFFFF
This parameter identifies the ZigBee network. This should be set to a value between 0 and 0x3FFF. Networks that exist in the same vicinity must have different values for this parameter. It can be set to a special value of 0xFFFF to indicate “don’t care”."
As I understand the 0xFFFF is the best value. The stick set the PAN Id by himself. Why do you need to define yourself the PAN Id?

"4.2.4.2 ZCD_NV_CHANLIST
Configuration ID: 0x0084; Size: 4 bytes; Default value: 0x00000800
This parameter is a bit mask of the channels on which this network can operate (note that multiple channels can be selected). See section 4.5.16 for a table of the bitmap representation that maps to each channel. Multiple networks that exist in the same vicinity are encouraged to have different values.
If multiple channels are selected, the coordinator will pick one of the channels for network operation. First, an energy scan is performed on each channel and those channels with a high energy level are discarded. Then, the coordinator determines the number of existing ZigBee networks on each of the remaining channels and picks the one with the fewest networks. For routers and end-devices, the device will simply scan all the selected channels until it finds the ZigBee network."
As I understand the best way is to set the full range of channels and the ZB-stick chooses some channel by himself accordingly to the algorithm above. Why do you need to define yourself the channel Id?

About reset setting
"I don't think setting this in this way is the right way to do this" - Why do you think so? I think that user should have the way to reset the system in case of incorrect system work.

"Can I suggest for now to break the PR into two" - Yes, you can.
The devices are presented in "New devices were added"-commit and in links
http://smartenit.com/product/zbht-2/
http://smartenit.com/product/zbmplug15/

Besides, I have some questions:

1) I would like to know why have you changed the binding architecture?
IMHO the binding with the device channel (cluster + attribute) determination (as was earlier) is more flexible against the binding with the device determination. If some new device appears then it should be added to some *.xml and the binding should be rebuilded.

2) How can I move the detected devices to "Control" tab? I "Add as thing" for each of them and they are replaced from the "Inbox" tab to the "Configuration->Things" tab. But I do not see them in "Control" tab.

Thanks

**Comment by cdjackson** [comment]
> "I thought channel 11 was default" - yes, you are right, channel 11 is default.
> The channel 19 is correct for the 2531 and for the 2538 - I worked with both ZB-sticks.
> 
> Just to confirm - channel 11 is default for the 2351 and 19 for the 2538? I think that we should use 11 as I think this is a more normal default used by other systems?
> 
> As I understand the 0xFFFF is the best value. The stick set the PAN Id by himself. Why do you need to define yourself the PAN Id?
> 
> I don’t think we should stop a user selecting a channel if they want. The PANid and channel are ‘advanced parameters’ so they are not displayed unless you are in advanced mode anyway.
> 
> "I don't think setting this in this way is the right way to do this" - Why do you think so? I think that user should have the way to reset the system in case of incorrect system work.
> 
> Yes - I agree the user should be able to reset - I just don’t think that using a string is right for starters, and secondly I would prefer to use a system that sends a reset command rather than sets the binding into reset mode. In your implementation, the system can get stuck in reset mode until the user spots the error.
> 
> "Can I suggest for now to break the PR into two" - Yes, you can.
> 
> Thanks :)
> 
> Besides, I have some questions:
> 
> 1) I would like to know why have you changed the binding architecture?
> IMHO the binding with the device channel (cluster + attribute) determination (as was earlier) is more flexible against the binding with the device determination. If some new device appears then it should be added to some *.xml and the binding should be rebuilded.
> 
> In ESH, a ‘Thing’ is defined as a physical device. Previously, this was not the case - a ‘thing’ was an endpoint. This starts to cause problems with more complex devices - e.g. ones that have 5 endpoints - one for temperature, one for humidity, one for light sensor, one for occupancy, and one for a tamper switch. In the old system, these would each show up as a separate thing, and this is not right.

I agree the requirement for XML files is not nice and this will be removed - In the near future I will implement a better mechanism that does not require the XML files, but this requires some changes to the ESH core.

> 2) How can I move the detected devices to "Control" tab? I "Add as thing" for each of them and they are replaced from the "Inbox" tab to the "Configuration->Things" tab. But I do not see them in "Control" tab.
> 
> Add them to a group that is shown in the control tab

**Comment by AlexeyIvantsov** [comment]
By the way

1) I see the strange implementation of the ZDO_MGMT_PERMIT_JOIN_REQ class.
Accordingly to ZNP document the command has 4 bytes in length: DstAddr (2 bytes) + Duration (1 byte) + TCSignificance (1 byte) and in the class implementation I see also 'AddrMode' field (1 byte) before DstAddr. Is it right?

2) I can not create any group by unknown reason: a click on "Add group" label does not get some result, I have no logs for this action. Do I need to perform some additional action for some group creation?

**Comment by cdjackson** [comment]
Do you mean that there is the address_mode byte in the packet? If so, then I would agree that this doesn’t look correct… I’ll have a better look over the weekend...

**Pull request closed without merging**
