### PR TITLE
merge openhab:master into cdjackson:zigbee

### PR DESCRIPTION
**Pull request by derabbink**
https://github.com/openhab/openhab2-addons/pull/779/ has been open for a while and now has a merge conflict. This PR fixes the conflict by merging `openhab:master` into `cdjackson:zigbee`.
This really only touches `addons/binding/pom.xml` in commit `1044c86`.

### CODE REVIEW

**Comment by derabbink** [comment]
I apologize for this - what turned out to be a - convoluted PR. Like the initial comment states, you can use the changes to `addons/binding/pom.xml` in commit 1044c86 to resolve the merge conflict in https://github.com/openhab/openhab2-addons/pull/779

**Comment by cdjackson** [comment]
Thanks, but am going to close this as the repo will be moved an the pom will not be relevant.

**Comment by derabbink** [comment]
Can you please reveal what the concrete plans for the further development of this binding are? I am happy to contribute, as I have a CC2531, and tons of ZigBee HA devices (switches, lights, IAS sensors, thermostats, etc) to test with.

**Comment by cdjackson** [comment]
The binding is being moved to a separate repository - I hope to get a first version available very soon (i.e. in a few days I hope) to handle lights in the first instance. This PR will be closed.

**Pull request closed without merging**
